### PR TITLE
Updated With Write and WriteLine

### PR DESCRIPTION
**Pull request by arunpratap26**
Added the difference between the Write and the WriteLine methods.

### CODE REVIEW

**Comment by knugi0123** [comment]
Noted! Thanks for your help. We will merge it as soon as possible if needed.

**Comment by knugi0123** [comment]
Thanks again! Your contribution makes this project even better!
In addition, you are welcome to open more pull requests.
At last, sorry for being late to review your request. Hope to see you again!

**Comment by arunpratap26** [comment]
sure and thanks

**Comment by arunpratap26** [comment]
tell me if you need any help regarding c sharp  in future it will be my pleasure to contribute something

**Pull request merged**
